type -> INT
type -> FLOAT
type -> BOOL
params -> param paramsOpt
params ->
paramsOpt -> COMMA param paramsOpt
paramsOpt ->
param -> ID typeId
typeId -> COLON type
fator -> ID fatorLinha
fator -> FALSE
fator -> NIL
fator -> TRUE
fator -> NUMBER
fator -> STRING
fator -> MINUS fator
fator -> LPAREN expOr RPAREN
fator -> tabelaCtr
fatorLinha -> DOT ID fatorLinha
fatorLinha -> LBRACKET expOr RBRACKET fatorLinha
fatorLinha -> LPAREN argsList RPAREN fatorLinha
fatorLinha ->
termo -> fator termoLinha
termoLinha -> MULT fator termoLinha
termoLinha -> DIV fator termoLinha
termoLinha -> MOD fator termoLinha
termoLinha ->
exp -> termo expLinha
expLinha -> PLUS termo expLinha
expLinha -> MINUS termo expLinha
expLinha ->
expRel -> exp expRelLinha
expRelLinha -> EQ exp expRelLinha
expRelLinha -> NEQ exp expRelLinha
expRelLinha -> LESSTHAN exp expRelLinha
expRelLinha -> LESSEQ exp expRelLinha
expRelLinha -> GREATERTHAN exp expRelLinha
expRelLinha -> GREATEREQ exp expRelLinha
expRelLinha ->
expNot -> NOT expNot
expNot -> expRel
expAnd -> expNot expAndLinha
expAndLinha -> AND expNot expAndLinha
expAndLinha ->
expOr -> expAnd expOrLinha
expOrLinha -> OR expAnd expOrLinha
expOrLinha ->
cmd -> ID cmdLinha cmdLinhaLinha
cmd -> ifCmd
cmd -> whileCmd
cmd -> localCmd
cmd -> returnCmd
cmd -> functionCmd
cmdLinha -> DOT ID cmdLinha
cmdLinha -> LBRACKET expOr RBRACKET cmdLinha
cmdLinha ->
cmdLinhaLinha -> ASSIGN expOr
cmdLinhaLinha -> LPAREN argsList RPAREN
listaCmd -> cmd listaCmdLinha
listaCmdLinha -> cmd listaCmdLinha
listaCmdLinha ->
listaCmdOpt -> listaCmd
listaCmdOpt ->
ifCmd -> IF expOr THEN listaCmdOpt ifLinha
ifLinha -> ELSEIF expOr THEN listaCmdOpt ifLinha
ifLinha -> ELSE listaCmdOpt END
ifLinha -> END
whileCmd -> WHILE expOr DO listaCmdOpt END
localCmd -> LOCAL ID typeId localLinha
localLinha -> ASSIGN expOr
localLinha ->
returnCmd -> RETURN expOr
functionCmd -> FUNCTION ID LPAREN params RPAREN typeId listaCmdOpt END