fator -> ID
fator -> FALSE
fator -> NIL
fator -> TRUE
fator -> NUMBER
fator -> STRING
fator -> LPAREN expOr RPAREN
fator -> functionCall

termo -> fator termo'

termo' -> MULT fator termo'
termo' -> DIV fator termo'
termo' -> MOD fator termo'
termo' -> EPSILON

exp -> termo exp'

exp' -> PLUS termo exp'
exp' -> MINUS termo exp'
exp' -> EPSILON

expRel -> exp expRel'

expRel' -> EQ exp expRel'
expRel' -> NEQ exp expRel'
expRel' -> LESSTHAN exp expRel'
expRel' -> LESSEQ exp expRel'
expRel' -> GREATERTHAN exp expRel'
expRel' -> GREATEREQ exp expRel'
expRel' -> EPSILON

expAnd -> expRel expAnd'

expAnd' -> AND expRel expAnd'
expAnd' -> EPSILON

expOr -> expAnd expOr'

expOr' -> OR expAnd expOr'
enpOr' -> EPSILON

atribuicao -> ID ASSIGN expOr

cmd -> atribuicao
cmd -> ifCmd
cmd -> whileCmd
cmd -> localCmd
cmd -> returnCmd
cmd -> functionCmd
cmd -> functionCall

lista_cmd -> cmd lista_cmd'

lista_cmd' -> cmd lista_cmd'
lista_cmd' -> EPSILON

program -> lista_cmd EOF

ifCmd -> IF expOr THEN lista_cmd elseifList elseCmd END

elseifList -> ELSEIF expOr THEN lista_cmd elseifList
elseifList -> EPSILON

elseCmd -> ELSE lista_cmd
elseCmd -> EPSILON

whileCmd -> WHILE expOr DO lista_cmd END

localCmd -> LOCAL atribuicao
localCmd -> LOCAL ID

returnCmd -> RETURN expOr
returnCmd -> RETURN

functionCmd -> FUNCTION ID LPAREN paramList RPAREN lista_cmd END

paramList -> ID paramList'
paramList -> EPSILON

paramList' -> COMMA ID paramList'
paramList' -> EPSILON

functionCall -> ID LPAREN argsList RPAREN

argsList -> expOr argsList'
argsList -> EPSILON

argsList' -> COMMA expOr argsList'
argsList' -> EPSILON