fator -> ID
fator -> FALSE
fator -> NIL
fator -> TRUE
fator -> NUMBER
fator -> STRING
fator -> LPAREN expOr RPAREN
fator -> functionCall
termo -> fator termoLinha
termoLinha -> MULT fator termoLinha
termoLinha -> DIV fator termoLinha
termoLinha -> MOD fator termoLinha
termoLinha ->
exp -> termo expLinha
expLinha -> PLUS termo expLinha
expLinha -> MINUS termo expLinha
expLinha ->
expRel -> exp expRelLinha
expRelLinha -> EQ exp expRelLinha
expRelLinha -> NEQ exp expRelLinha
expRelLinha -> LESSTHAN exp expRelLinha
expRelLinha -> LESSEQ exp expRelLinha
expRelLinha -> GREATERTHAN exp expRelLinha
expRelLinha -> GREATEREQ exp expRelLinha
expRelLinha ->
expAnd -> expRel expAndLinha
expAndLinha -> AND expRel expAndLinha
expAndLinha ->
expOr -> expAnd expOrLinha
expOrLinha -> OR expAnd expOrLinha
expOrLinha ->
atribuicao -> ID ASSIGN expOr
cmd -> atribuicao
cmd -> ifCmd
cmd -> whileCmd
cmd -> localCmd
cmd -> returnCmd
cmd -> functionCmd
cmd -> functionCall
listaCmd -> cmd listaCmdLinha
listaCmdLinha -> cmd listaCmdLinha
listaCmdLinha ->
program -> listaCmd EOF
ifCmd -> IF expOr THEN listaCmd elseifList elseCmd END
elseifList -> ELSEIF expOr THEN listaCmd elseifList
elseifList ->
elseCmd -> ELSE listaCmd
elseCmd ->
whileCmd -> WHILE expOr DO listaCmd END
localCmd -> LOCAL atribuicao
localCmd -> LOCAL ID
returnCmd -> RETURN expOr
returnCmd -> RETURN
functionCmd -> FUNCTION ID LPAREN paramList RPAREN listaCmd END
paramList -> ID paramListLinha
paramList ->
paramListLinha -> COMMA ID paramListLinha
paramListLinha ->
functionCall -> ID LPAREN argsList RPAREN
argsList -> expOr argsListLinha
argsList ->
argsListLinha -> COMMA expOr argsListLinha
argsListLinha ->
