S -> program
program -> listaCmd
fator -> ID fatorLinha
fator -> FALSE
fator -> NIL
fator -> TRUE
fator -> NUMBER
fator -> STRING
fator -> LPAREN expOr RPAREN
fatorLinha -> LPAREN argsList RPAREN
fatorLinha -> ''
termo -> fator termoLinha
termoLinha -> MULT fator termoLinha
termoLinha -> DIV fator termoLinha
termoLinha -> MOD fator termoLinha
termoLinha -> ''
exp -> termo expLinha
expLinha -> PLUS termo expLinha
expLinha -> MINUS termo expLinha
expLinha -> ''
expRel -> exp expRelLinha
expRelLinha -> EQ exp expRelLinha
expRelLinha -> NEQ exp expRelLinha
expRelLinha -> LESSTHAN exp expRelLinha
expRelLinha -> LESSEQ exp expRelLinha
expRelLinha -> GREATERTHAN exp expRelLinha
expRelLinha -> GREATEREQ exp expRelLinha
expRelLinha -> ''
expAnd -> expRel expAndLinha
expAndLinha -> AND expRel expAndLinha
expAndLinha -> ''
expOr -> expAnd expOrLinha
expOrLinha -> OR expAnd expOrLinha
expOrLinha -> ''
atribuicao -> ID ASSIGN expOr
cmd -> ID cmdLinha
cmd -> ifCmd
cmd -> whileCmd
cmd -> localCmd
cmd -> returnCmd
cmd -> functionCmd
cmdLinha -> ASSIGN expOr
cmdLinha -> LPAREN argsList RPAREN
listaCmd -> listaCmd SEMICOLON cmd
listaCmd -> cmd
ifCmd -> IF expOr THEN listaCmd ifLinha
ifLinha -> ELSEIF expOr THEN listaCmd ifLinha
ifLinha -> ELSE listaCmd END
ifLinha -> END
whileCmd -> WHILE expOr DO listaCmd END
localCmd -> LOCAL atribuicao
localCmd -> LOCAL ID
returnCmd -> RETURN expOr
functionCmd -> FUNCTION ID LPAREN paramList RPAREN listaCmd END
paramList -> ID paramListLinha
paramList -> ''
paramListLinha -> COMMA ID paramListLinha
paramListLinha -> ''
argsList -> expOr argsListLinha
argsList -> ''
argsListLinha -> COMMA expOr argsListLinha
argsListLinha -> ''