S -> program
program -> listaCmd
fator -> ID fatorLinha
fator -> FALSE
fator -> NIL
fator -> TRUE
fator -> NUMBER
fator -> STRING
fator -> MINUS fator
fator -> LPAREN expOr RPAREN
fator -> tabelaCtr
fatorLinha -> DOT ID fatorLinha
fatorLinha -> LBRACKET expOr RBRACKET fatorLinha
fatorLinha -> LPAREN argsList RPAREN fatorLinha
fatorLinha ->
termo -> fator termoLinha
termoLinha -> MULT fator termoLinha
termoLinha -> DIV fator termoLinha
termoLinha -> MOD fator termoLinha
termoLinha ->
exp -> termo expLinha
expLinha -> PLUS termo expLinha
expLinha -> MINUS termo expLinha
expLinha ->
expRel -> exp expRelLinha
expRelLinha -> EQ exp expRelLinha
expRelLinha -> NEQ exp expRelLinha
expRelLinha -> LESSTHAN exp expRelLinha
expRelLinha -> LESSEQ exp expRelLinha
expRelLinha -> GREATERTHAN exp expRelLinha
expRelLinha -> GREATEREQ exp expRelLinha
expRelLinha ->
expNot -> NOT expNot
expNot -> expRel
expAnd -> expNot expAndLinha
expAndLinha -> AND expNot expAndLinha
expAndLinha ->
expOr -> expAnd expOrLinha
expOrLinha -> OR expAnd expOrLinha
expOrLinha ->
cmd -> ID cmdLinha cmdLinhaLinha
cmd -> ifCmd
cmd -> whileCmd
cmd -> localCmd
cmd -> returnCmd
cmd -> functionCmd
cmdLinha -> DOT ID cmdLinha
cmdLinha -> LBRACKET expOr RBRACKET cmdLinha
cmdLinha ->
cmdLinhaLinha -> ASSIGN expOr
cmdLinhaLinha -> LPAREN argsList RPAREN
listaCmd -> listaCmd cmd
listaCmd -> cmd
listaCmdOpt -> listaCmd
listaCmdOpt ->
ifCmd -> IF expOr THEN listaCmdOpt ifLinha
ifLinha -> ELSEIF expOr THEN listaCmdOpt ifLinha
ifLinha -> ELSE listaCmdOpt END
ifLinha -> END
whileCmd -> WHILE expOr DO listaCmdOpt END
localCmd -> LOCAL ID localLinha
localLinha -> ASSIGN expOr
localLinha ->
returnCmd -> RETURN expOr
functionCmd -> FUNCTION ID colonOpt LPAREN paramList RPAREN listaCmdOpt END
colonOpt -> COLON ID
colonOpt ->
paramList -> ID paramListLinha
paramList ->
paramListLinha -> COMMA ID paramListLinha
paramListLinha ->
argsList -> expOr argsListLinha
argsList ->
argsListLinha -> COMMA expOr argsListLinha
argsListLinha ->
tabelaCtr -> LCURLYBRACE tabelaLista RCURLYBRACE
tabelaCtr -> LCURLYBRACE RCURLYBRACE
tabelaElem -> expOr
tabelaElem -> ID ASSIGN expOr
tabelaLista -> tabelaElem tabelaListaLinha
tabelaListaLinha -> COMMA tabelaElem tabelaListaLinha
tabelaListaLinha ->